// Package transpiler implements the comment-hosted decorator transpiler.
//
// The model, in one breath: a user annotates any plain function with
// //@decorate doc comments; we rename that function to an unexported
// <name>Impl and generate a brand-new function with the original name and an
// identical signature that builds the decorator chain over <name>Impl. Every
// existing caller of the original name therefore transparently flows through
// the decorators — exactly like Python's fn = a(b(fn)).
//
// Strategy A (rename-and-wrap), end to end:
//
//  1. Parse every non-generated .go file in the directory with comments intact.
//  2. For each func declaration, read its doc group for //@decorate lines.
//  3. From the full *ast.FuncType, faithfully reproduce the signature (named,
//     unnamed, grouped and variadic params; zero/one/many results).
//  4. Surgically rename the original function to <name>Impl in place (a precise
//     text edit so the rest of the file — comments, formatting — is untouched)
//     and stamp a //deco:wrapper marker so re-runs are idempotent.
//  5. Emit a fully type-safe wrapper into <file>_gen.go, formatted with
//     go/format and carrying the standard "DO NOT EDIT" header.
//
// Only plain functions are supported in v1; methods (with receivers) are
// detected and rejected with a clear file:line error.
package transpiler

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"text/template"
)

// marker is the comment we stamp above a renamed function so that subsequent
// runs can recover the original (wrapper) name and know the rename is already
// done. It keeps generation idempotent. The "//word:" shape is a gofmt
// directive form, so gofmt leaves it untouched (no space inserted).
const marker = "//deco:wrapper "

// markerKey / annotationKey are the slash-stripped forms used when scanning doc
// comments, so we match regardless of any space gofmt inserts after "//".
const (
	markerKey     = "deco:wrapper"
	annotationKey = "@decorate"
	// importDirectiveKey introduces an import to inject into generated files so
	// that qualified decorators (pkg.Name) resolve, e.g.
	//   //deco:import "github.com/you/yourdecorators"
	//   //deco:import alias "github.com/you/yourdecorators"
	importDirectiveKey = "deco:import"
)

// generatedHeader marks files we own; we never scan these for annotations and
// always overwrite them wholesale.
const generatedHeader = "// Code generated by deco; DO NOT EDIT."

// decorator is a single parsed //@decorate annotation.
type decorator struct {
	name      string   // the (possibly qualified) decorator identifier, e.g. "logged" or "pkg.Logged"
	args      string   // rendered leading arguments, e.g. `"slow"`; empty when none
	argN      int      // number of leading arguments supplied
	line      int      // source line of the annotation, for diagnostics
	selectors []string // package selectors referenced (head + args), e.g. ["decorators"]
}

// job is one function that needs a generated wrapper.
type job struct {
	wrapperName string         // the original, public-facing name (e.g. Add)
	implName    string         // the renamed implementation (e.g. addImpl)
	decorators  []decorator    // in source (top-to-bottom) order
	fn          *ast.FuncType  // the full signature
	srcFile     string         // absolute path of the source file
	decl        *ast.FuncDecl  // the declaration (used for rename positions)
	needsRename bool           // false when a marker shows the rename already happened
}

// Output is one file's worth of generated content, keyed by the absolute path
// it represents inside the package: either a transformed (renamed) original or
// a generated <file>_gen.go wrapper.
type Output struct {
	Path    string // absolute path this content stands in for
	Content []byte
}

// analysis is the parsed, validated view of a package directory.
type analysis struct {
	fset       *token.FileSet
	srcNames   []string             // sorted, absolute source paths
	files      map[string]*ast.File // by absolute path
	jobsByFile map[string][]job     // by absolute path
	imports    map[string]string    // package selector -> import line, from //deco:import directives

	// fileImports maps each source path to that file's own imports
	// (selector -> import line), used to re-import types referenced by a
	// reproduced wrapper signature (e.g. http.ResponseWriter).
	fileImports map[string]map[string]string
}

// analyze performs steps 1–4: parse every non-generated .go file, build a
// package-wide view of declared functions, scan annotations, validate decorator
// references, and assemble the per-file job lists. It does not touch disk.
func analyze(dir string) (*analysis, error) {
	fset := token.NewFileSet()

	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", dir, err)
	}

	// Deterministic ordering everywhere: sort absolute paths up front.
	var srcNames []string
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") {
			continue
		}
		if strings.HasSuffix(name, "_gen.go") || strings.HasSuffix(name, "_test.go") {
			continue // never scan our own output or test files
		}
		abs, err := filepath.Abs(filepath.Join(dir, name))
		if err != nil {
			return nil, err
		}
		srcNames = append(srcNames, abs)
	}
	sort.Strings(srcNames)

	files := make(map[string]*ast.File, len(srcNames))
	for _, path := range srcNames {
		f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return nil, fmt.Errorf("parsing %s: %w", path, err)
		}
		files[path] = f
	}

	// funcArity maps every plain top-level function name in the package to its
	// value-parameter count, so we can resolve and arity-check bare decorators.
	funcArity := map[string]int{}
	for _, f := range files {
		for _, decl := range f.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Recv != nil {
				continue
			}
			funcArity[fn.Name.Name] = paramCount(fn.Type)
		}
	}

	// Collect //deco:import directives so qualified decorators (pkg.Name) can be
	// resolved by injecting the right import into the generated files.
	importDirectives, err := collectImportDirectives(srcNames, files, fset)
	if err != nil {
		return nil, err
	}

	// Each file's own imports, so a wrapper can re-import the packages its
	// signature types come from.
	fileImports := make(map[string]map[string]string, len(srcNames))
	for _, path := range srcNames {
		fileImports[path] = importsOf(files[path])
	}

	jobsByFile := map[string][]job{}
	for _, path := range srcNames {
		f := files[path]
		for _, decl := range f.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Doc == nil {
				continue
			}
			decs, wrapperOverride := parseAnnotations(fn.Doc, fset)
			if len(decs) == 0 {
				continue
			}
			pos := fset.Position(fn.Pos())
			if fn.Recv != nil {
				return nil, fmt.Errorf("%s:%d: deco v1 supports plain functions only; "+
					"%q has a receiver and cannot be decorated", pos.Filename, pos.Line, fn.Name.Name)
			}

			for _, d := range decs {
				if err := validateDecorator(d, funcArity, fileImports[path], importDirectives, pos.Filename); err != nil {
					return nil, err
				}
			}

			j := job{decorators: decs, fn: fn.Type, srcFile: path, decl: fn}
			if wrapperOverride != "" {
				// Already renamed on a previous (on-disk) run; the marker carries
				// the public name and the current decl name is the impl.
				j.wrapperName = wrapperOverride
				j.implName = fn.Name.Name
				j.needsRename = false
			} else {
				j.wrapperName = fn.Name.Name
				j.implName = implName(fn.Name.Name)
				j.needsRename = true
			}
			jobsByFile[path] = append(jobsByFile[path], j)
		}
	}
	return &analysis{
		fset:        fset,
		srcNames:    srcNames,
		files:       files,
		jobsByFile:  jobsByFile,
		imports:     importDirectives,
		fileImports: fileImports,
	}, nil
}

// transform produces, in memory, every file needed to realise the decorators:
// transformed (renamed) originals plus the generated wrappers. Nothing is
// written; callers decide whether to materialise the outputs as real files
// (Generate) or feed them to the build untouched-on-disk (Overlay).
func transform(dir string) ([]Output, error) {
	a, err := analyze(dir)
	if err != nil {
		return nil, err
	}
	var outputs []Output
	for _, path := range a.srcNames {
		jobs := a.jobsByFile[path]
		if len(jobs) == 0 {
			continue
		}
		// Transformed original — only when something actually needs renaming.
		renamed, changed, err := renameBytes(path, jobs, a.fset)
		if err != nil {
			return nil, err
		}
		if changed {
			outputs = append(outputs, Output{Path: path, Content: renamed})
		}
		// Generated wrapper, with any imports its decorators and reproduced
		// signatures need.
		imports := importsForFile(jobs, a.fileImports[path], a.imports)
		gen, err := genBytes(path, a.files[path].Name.Name, jobs, imports, a.fset)
		if err != nil {
			return nil, err
		}
		base := strings.TrimSuffix(filepath.Base(path), ".go")
		genPath := filepath.Join(filepath.Dir(path), base+"_gen.go")
		outputs = append(outputs, Output{Path: genPath, Content: gen})
	}
	return outputs, nil
}

// packageDirs returns every directory at or under root that holds Go source we
// should scan, sorted for deterministic processing. It is what lets deco handle
// a multi-package tree (e.g. a router with handlers/ and middleware/ folders),
// matching the `./...` reach of `go build`. vendor, testdata, node_modules and
// hidden directories are skipped.
func packageDirs(root string) ([]string, error) {
	set := map[string]bool{}
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if path != root {
				switch name := d.Name(); {
				case strings.HasPrefix(name, "."), name == "vendor", name == "testdata", name == "node_modules":
					return filepath.SkipDir
				}
			}
			return nil
		}
		name := d.Name()
		if strings.HasSuffix(name, ".go") &&
			!strings.HasSuffix(name, "_gen.go") && !strings.HasSuffix(name, "_test.go") {
			set[filepath.Dir(path)] = true
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	dirs := make([]string, 0, len(set))
	for d := range set {
		dirs = append(dirs, d)
	}
	sort.Strings(dirs)
	return dirs, nil
}

// transformTree runs transform over every package directory at or under root
// and concatenates the results, so decorators are realised across the whole
// multi-folder project, not just the top directory.
func transformTree(root string) ([]Output, error) {
	dirs, err := packageDirs(root)
	if err != nil {
		return nil, err
	}
	var all []Output
	for _, d := range dirs {
		outputs, err := transform(d)
		if err != nil {
			return nil, err
		}
		all = append(all, outputs...)
	}
	return all, nil
}

// Generate runs the transpiler and MATERIALISES the results on disk: it renames
// originals in place (stamping the idempotency marker) and writes the
// <file>_gen.go wrappers next to them. It processes the whole package tree
// under dir.
func Generate(dir string) error {
	outputs, err := transformTree(dir)
	if err != nil {
		return err
	}
	for _, o := range outputs {
		if err := os.WriteFile(o.Path, o.Content, 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", o.Path, err)
		}
	}
	return nil
}

// Overlay runs the transpiler but keeps the generated code OUT of the source
// tree. It writes the transformed originals and the wrappers to a temp
// directory and returns the path to a `go build -overlay` JSON file mapping each
// real package path to its shadow content. The user's .go files are never
// modified and no _gen.go ever lands in the package directory — the decoration
// exists only for the duration of the build.
//
// cleanup removes the temp directory; callers should defer it. It processes the
// whole package tree under dir, so every package's decorators are injected.
func Overlay(dir string) (overlayPath string, cleanup func(), err error) {
	outputs, err := transformTree(dir)
	if err != nil {
		return "", nil, err
	}
	tmp, err := os.MkdirTemp("", "deco-overlay-")
	if err != nil {
		return "", nil, err
	}
	cleanup = func() { os.RemoveAll(tmp) }

	// The overlay's Replace map points each real package path at a shadow file.
	// A key need not exist on disk, which is exactly how we *inject* the
	// <file>_gen.go wrappers as new members of the package.
	replace := make(map[string]string, len(outputs))
	for i, o := range outputs {
		shadow := filepath.Join(tmp, fmt.Sprintf("%d_%s", i, filepath.Base(o.Path)))
		if err := os.WriteFile(shadow, o.Content, 0o644); err != nil {
			cleanup()
			return "", nil, err
		}
		replace[o.Path] = shadow
	}

	overlayPath = filepath.Join(tmp, "overlay.json")
	doc := struct{ Replace map[string]string }{Replace: replace}
	data, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		cleanup()
		return "", nil, err
	}
	if err := os.WriteFile(overlayPath, data, 0o644); err != nil {
		cleanup()
		return "", nil, err
	}
	return overlayPath, cleanup, nil
}

// parseAnnotations scans a doc group for //@decorate lines (and the
// //deco:wrapper marker). It returns the decorators in source order plus
// the wrapper-name override carried by the marker (empty if absent).
func parseAnnotations(doc *ast.CommentGroup, fset *token.FileSet) ([]decorator, string) {
	var decs []decorator
	var wrapperOverride string
	for _, c := range doc.List {
		// Normalise away the leading slashes and any space gofmt may have
		// inserted, so "//@decorate x" and "// @decorate x" both match.
		content := strings.TrimSpace(strings.TrimLeft(c.Text, "/"))
		switch {
		case strings.HasPrefix(content, markerKey):
			wrapperOverride = strings.TrimSpace(strings.TrimPrefix(content, markerKey))
		case strings.HasPrefix(content, annotationKey):
			spec := strings.TrimSpace(strings.TrimPrefix(content, annotationKey))
			if spec == "" {
				continue
			}
			name, args, argN, selectors := splitDecoratorSpec(spec)
			decs = append(decs, decorator{
				name:      name,
				args:      args,
				argN:      argN,
				line:      fset.Position(c.Slash).Line,
				selectors: selectors,
			})
		}
	}
	return decs, wrapperOverride
}

// splitDecoratorSpec parses a decorator spec like `timing("slow")` or
// `pkg.Logged` into (name, renderedArgs, argCount, packageSelectors). It parses
// the spec as a Go expression so that qualified names (pkg.Foo), multiple
// arguments, and nested calls are all handled robustly. If parsing fails, it
// falls back to treating the whole spec as a bare name.
func splitDecoratorSpec(spec string) (name, args string, argN int, selectors []string) {
	expr, err := parser.ParseExpr(spec)
	if err != nil {
		return spec, "", 0, nil
	}
	selectors = exprSelectors(expr)
	switch e := expr.(type) {
	case *ast.CallExpr:
		var parts []string
		for _, a := range e.Args {
			parts = append(parts, exprString(a))
		}
		return exprString(e.Fun), strings.Join(parts, ", "), len(e.Args), selectors
	default:
		return exprString(expr), "", 0, selectors
	}
}

// exprSelectors returns the distinct leading package selectors used anywhere in
// expr, e.g. `pkg.Logged(other.Arg)` -> ["other", "pkg"] (sorted).
func exprSelectors(expr ast.Expr) []string {
	seen := map[string]bool{}
	var out []string
	ast.Inspect(expr, func(n ast.Node) bool {
		if sel, ok := n.(*ast.SelectorExpr); ok {
			if id, ok := sel.X.(*ast.Ident); ok && !seen[id.Name] {
				seen[id.Name] = true
				out = append(out, id.Name)
			}
		}
		return true
	})
	sort.Strings(out)
	return out
}

// isQualified reports whether a decorator name is package-qualified (pkg.Name).
func isQualified(name string) bool { return strings.Contains(name, ".") }

// headSelector returns the package selector of a qualified decorator name, i.e.
// the identifier before the first dot ("pkg" for "pkg.Logged").
func headSelector(name string) string {
	if sel, _, found := strings.Cut(name, "."); found {
		return sel
	}
	return ""
}

// validateDecorator checks that a decorator reference is usable. A qualified
// (pkg.Name) decorator must have a matching //deco:import directive so the
// generated file can import its package; its arity is not checked, since its
// declaration lives outside the scanned package. A bare name must resolve to a
// function in the package, with an arity matching the supplied leading args.
func validateDecorator(d decorator, funcArity map[string]int, fileImports, directives map[string]string, file string) error {
	if isQualified(d.name) {
		sel := headSelector(d.name)
		// Resolvable if the source file already imports the package, or a
		// //deco:import directive names it.
		if _, ok := fileImports[sel]; ok {
			return nil
		}
		if _, ok := directives[sel]; ok {
			return nil
		}
		return fmt.Errorf("%s:%d: qualified decorator %q needs an import directive; "+
			"add `//deco:import \"path/to/%s\"` (or `//deco:import %s \"path/...\"`) to a file in this package",
			file, d.line, d.name, sel, sel)
	}
	params, ok := funcArity[d.name]
	if !ok {
		return fmt.Errorf("%s:%d: decorator %q not found in package", file, d.line, d.name)
	}
	// A decorator takes its leading args plus exactly one wrapped function.
	want := d.argN + 1
	if params != want {
		return fmt.Errorf("%s:%d: decorator %q has wrong arity: it declares %d parameter(s) "+
			"but the annotation supplies %d leading arg(s) (expected %d total: args + the wrapped fn)",
			file, d.line, d.name, params, d.argN, want)
	}
	return nil
}

// collectImportDirectives scans every comment in the package for
// //deco:import directives and returns a map from package selector to the
// import line to emit. Two forms are accepted:
//
//	//deco:import "github.com/you/pkg"          // selector = "pkg" (last path element)
//	//deco:import alias "github.com/you/pkg"    // selector = "alias"
func collectImportDirectives(srcNames []string, files map[string]*ast.File, fset *token.FileSet) (map[string]string, error) {
	out := map[string]string{}
	// Iterate files in sorted order for deterministic error reporting.
	for _, path := range srcNames {
		f := files[path]
		for _, cg := range f.Comments {
			for _, c := range cg.List {
				content := strings.TrimSpace(strings.TrimLeft(c.Text, "/"))
				if !strings.HasPrefix(content, importDirectiveKey) {
					continue
				}
				spec := strings.TrimSpace(strings.TrimPrefix(content, importDirectiveKey))
				sel, line, err := parseImportDirective(spec)
				if err != nil {
					p := fset.Position(c.Slash)
					return nil, fmt.Errorf("%s:%d: bad //deco:import directive: %w", p.Filename, p.Line, err)
				}
				out[sel] = line
			}
		}
	}
	return out, nil
}

// parseImportDirective parses the body of a //deco:import directive into the
// package selector it introduces and the canonical import line to emit.
func parseImportDirective(spec string) (selector, importLine string, err error) {
	fields := strings.Fields(spec)
	switch len(fields) {
	case 1: // "path"
		path, uerr := strconv.Unquote(fields[0])
		if uerr != nil {
			return "", "", fmt.Errorf("expected a quoted import path, got %q", fields[0])
		}
		return lastPathElement(path), strconv.Quote(path), nil
	case 2: // alias "path"
		alias := fields[0]
		path, uerr := strconv.Unquote(fields[1])
		if uerr != nil {
			return "", "", fmt.Errorf("expected a quoted import path, got %q", fields[1])
		}
		return alias, alias + " " + strconv.Quote(path), nil
	default:
		return "", "", fmt.Errorf("expected `\"path\"` or `alias \"path\"`, got %q", spec)
	}
}

// lastPathElement returns the conventional package selector for an import path
// (its final element), e.g. "github.com/you/decorators" -> "decorators".
func lastPathElement(path string) string {
	if i := strings.LastIndexByte(path, '/'); i >= 0 {
		return path[i+1:]
	}
	return path
}

// importsOf returns a file's imports as a selector -> import-line map. Blank and
// dot imports are skipped (they introduce no usable selector).
func importsOf(f *ast.File) map[string]string {
	out := map[string]string{}
	for _, spec := range f.Imports {
		path, err := strconv.Unquote(spec.Path.Value)
		if err != nil {
			continue
		}
		sel := lastPathElement(path)
		line := strconv.Quote(path)
		if spec.Name != nil {
			name := spec.Name.Name
			if name == "_" || name == "." {
				continue
			}
			sel = name
			line = name + " " + strconv.Quote(path)
		}
		out[sel] = line
	}
	return out
}

// signatureSelectors returns the distinct package selectors referenced by a
// function's parameter and result types (e.g. "http" for http.ResponseWriter),
// so the generated wrapper can re-import them.
func signatureSelectors(fn *ast.FuncType) []string {
	seen := map[string]bool{}
	var out []string
	collect := func(fl *ast.FieldList) {
		if fl == nil {
			return
		}
		for _, f := range fl.List {
			ast.Inspect(f.Type, func(n ast.Node) bool {
				if sel, ok := n.(*ast.SelectorExpr); ok {
					if id, ok := sel.X.(*ast.Ident); ok && !seen[id.Name] {
						seen[id.Name] = true
						out = append(out, id.Name)
					}
				}
				return true
			})
		}
	}
	collect(fn.Params)
	collect(fn.Results)
	return out
}

// importsForFile returns the sorted, de-duplicated import lines a generated file
// needs: the packages of its qualified decorators AND of the types in its
// reproduced wrapper signatures. Selectors are resolved against the source
// file's own imports first, then the package's //deco:import directives. Only
// referenced selectors are included, so generated files never carry an unused
// import.
func importsForFile(jobs []job, fileImports, directives map[string]string) []string {
	used := map[string]bool{}
	for _, j := range jobs {
		for _, d := range j.decorators {
			for _, sel := range d.selectors {
				used[sel] = true
			}
		}
		for _, sel := range signatureSelectors(j.fn) {
			used[sel] = true
		}
	}
	seen := map[string]bool{}
	var lines []string
	for sel := range used {
		line, ok := fileImports[sel]
		if !ok {
			line, ok = directives[sel]
		}
		if ok && !seen[line] {
			seen[line] = true
			lines = append(lines, line)
		}
	}
	sort.Strings(lines)
	return lines
}

// renameBytes returns the source file's bytes with each decorated function
// renamed to its impl name and a wrapper marker stamped above it. It edits text
// directly (using AST node offsets) instead of reprinting the AST, so untouched
// code, comments and formatting are preserved byte-for-byte. changed reports
// whether any rename was actually applied.
func renameBytes(path string, jobs []job, fset *token.FileSet) (out []byte, changed bool, err error) {
	src, err := os.ReadFile(path)
	if err != nil {
		return nil, false, fmt.Errorf("reading %s: %w", path, err)
	}

	type edit struct {
		start, end int
		text       string
	}
	var edits []edit
	for _, j := range jobs {
		if !j.needsRename {
			continue
		}
		// Replace the function name identifier.
		nameStart := fset.Position(j.decl.Name.Pos()).Offset
		nameEnd := fset.Position(j.decl.Name.End()).Offset
		edits = append(edits, edit{nameStart, nameEnd, j.implName})

		// Insert the marker on its own line directly above the func keyword, so
		// it stays attached to the function as part of its doc on re-parse.
		// FuncDecl.Pos() is the func keyword (column 0 for a top-level func).
		funcStart := fset.Position(j.decl.Pos()).Offset
		edits = append(edits, edit{funcStart, funcStart, marker + j.wrapperName + "\n"})
	}
	if len(edits) == 0 {
		return src, false, nil
	}

	// Apply from the end of the file backwards so offsets stay valid. We do NOT
	// reformat: the edits are already gofmt-clean (a column-0 marker line and an
	// identifier swap), and skipping gofmt preserves the user's exact
	// //@decorate comments instead of letting gofmt rewrite them to "// @".
	sort.Slice(edits, func(i, k int) bool { return edits[i].start > edits[k].start })
	out = src
	for _, e := range edits {
		out = append(out[:e.start:e.start], append([]byte(e.text), out[e.end:]...)...)
	}
	return out, true, nil
}

// genTemplate renders one generated file. Functions are emitted in source
// order; the whole file is run through go/format afterwards, so exact
// whitespace here does not matter.
var genTemplate = template.Must(template.New("gen").Parse(`{{.Header}}

package {{.Package}}
{{if .Imports}}
import (
{{range .Imports}}	{{.}}
{{end}})
{{end}}
{{range .Funcs}}
// {{.ChainVar}} is {{.WrapperName}}'s decorator chain, built ONCE at package
// init (like Python's fn = a(b(fn))) — so construction-time side effects such
// as route registration run at startup, and the reflection wrappers are created
// only once rather than on every call.
var {{.ChainVar}} = {{.Chain}}

func {{.WrapperName}}({{.Params}}){{if .Results}} {{.Results}}{{end}} {
	{{.Ret}}{{.ChainVar}}({{.CallArgs}})
}
{{end}}`))

type genFunc struct {
	WrapperName string
	ChainVar    string // package-level var holding the built chain
	Params      string
	Results     string
	Ret         string // "return " or ""
	Chain       string // decorator chain expression over the impl
	CallArgs    string // forwarded argument list
}

type genData struct {
	Header  string
	Package string
	Imports []string
	Funcs   []genFunc
}

// genBytes builds the formatted contents of <base>_gen.go for one source
// file's jobs (in memory; no write). imports is the sorted set of import lines
// the generated code needs (for qualified decorators).
func genBytes(srcPath, pkg string, jobs []job, imports []string, fset *token.FileSet) ([]byte, error) {
	data := genData{Header: generatedHeader, Package: pkg, Imports: imports}
	for _, j := range jobs {
		params, callArgs := renderParams(j.fn, fset)
		gf := genFunc{
			WrapperName: j.wrapperName,
			ChainVar:    j.implName + "Decorated",
			Params:      params,
			Results:     renderResults(j.fn, fset),
			Chain:       buildChain(j),
			CallArgs:    callArgs,
		}
		if j.fn.Results != nil && len(j.fn.Results.List) > 0 {
			gf.Ret = "return "
		}
		data.Funcs = append(data.Funcs, gf)
	}

	var buf bytes.Buffer
	if err := genTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("rendering wrapper for %s: %w", srcPath, err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting generated code for %s:\n%s\n%w", srcPath, buf.String(), err)
	}
	return formatted, nil
}

// buildChain assembles the decorator chain over the impl function. Decorators
// are applied BOTTOM-UP: the last annotation is the innermost wrapper and the
// first (topmost) annotation is the outermost. Leading arguments are passed
// before the wrapped function, per the contract.
//
// For //@decorate logged then //@decorate timing("slow") over Add, this yields
//
//	logged(timing("slow", addImpl))
func buildChain(j job) string {
	expr := j.implName
	for i := len(j.decorators) - 1; i >= 0; i-- {
		d := j.decorators[i]
		if d.args == "" {
			expr = fmt.Sprintf("%s(%s)", d.name, expr)
		} else {
			expr = fmt.Sprintf("%s(%s, %s)", d.name, d.args, expr)
		}
	}
	return expr
}

// renderParams reproduces the parameter list verbatim (synthesising names where
// the original omitted them) and returns both the signature fragment and the
// matching forwarded-argument list. Variadic parameters are preserved and
// forwarded with `...`.
func renderParams(fn *ast.FuncType, fset *token.FileSet) (params, callArgs string) {
	var sigParts, argParts []string
	idx := 0
	for _, field := range fn.Params.List {
		typeStr := typeString(field.Type, fset)
		_, variadic := field.Type.(*ast.Ellipsis)

		if len(field.Names) == 0 {
			// Unnamed parameter — synthesise a stable name.
			name := fmt.Sprintf("p%d", idx)
			idx++
			sigParts = append(sigParts, name+" "+typeStr)
			argParts = append(argParts, forwardArg(name, variadic))
			continue
		}
		var names []string
		for _, n := range field.Names {
			name := n.Name
			if name == "_" {
				// Blank params still need a real name to be forwarded.
				name = fmt.Sprintf("p%d", idx)
			}
			idx++
			names = append(names, name)
			argParts = append(argParts, forwardArg(name, variadic))
		}
		sigParts = append(sigParts, strings.Join(names, ", ")+" "+typeStr)
	}
	return strings.Join(sigParts, ", "), strings.Join(argParts, ", ")
}

// forwardArg renders a single forwarded argument, appending `...` for the
// variadic parameter so the spread is preserved.
func forwardArg(name string, variadic bool) string {
	if variadic {
		return name + "..."
	}
	return name
}

// renderResults reproduces the result types. Names are dropped (they are
// irrelevant to a forwarding wrapper); multiple results are wrapped in parens.
func renderResults(fn *ast.FuncType, fset *token.FileSet) string {
	if fn.Results == nil || len(fn.Results.List) == 0 {
		return ""
	}
	var parts []string
	for _, field := range fn.Results.List {
		typeStr := typeString(field.Type, fset)
		// A field may carry several names sharing one type (e.g. (a, b int));
		// each contributes one result of that type.
		n := len(field.Names)
		if n == 0 {
			n = 1
		}
		for i := 0; i < n; i++ {
			parts = append(parts, typeStr)
		}
	}
	if len(parts) == 1 {
		return parts[0]
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

// paramCount returns the number of value parameters declared by a func type.
func paramCount(fn *ast.FuncType) int {
	if fn.Params == nil {
		return 0
	}
	count := 0
	for _, field := range fn.Params.List {
		if len(field.Names) == 0 {
			count++
		} else {
			count += len(field.Names)
		}
	}
	return count
}

// implName derives the unexported implementation name from a function name:
// the first rune is lower-cased and "Impl" is appended (Add -> addImpl).
func implName(name string) string {
	if name == "" {
		return "impl"
	}
	r := []rune(name)
	r[0] = lower(r[0])
	return string(r) + "Impl"
}

func lower(r rune) rune {
	if r >= 'A' && r <= 'Z' {
		return r + ('a' - 'A')
	}
	return r
}

// typeString renders a type expression to its Go source form using go/printer,
// which faithfully handles selectors, pointers, slices, maps, channels, func
// types, generics and ellipses.
func typeString(expr ast.Expr, fset *token.FileSet) string {
	return exprStringFset(expr, fset)
}

// exprString renders an expression parsed from an annotation spec (these have
// no real file positions, so a fresh empty FileSet is fine).
func exprString(expr ast.Expr) string {
	return exprStringFset(expr, token.NewFileSet())
}

func exprStringFset(expr ast.Expr, fset *token.FileSet) string {
	var buf bytes.Buffer
	// printer with no extra config emits compact, canonical type syntax.
	_ = printer.Fprint(&buf, fset, expr)
	return buf.String()
}
